/** Human-readable project files written next to the storyboard. */
import type { PlannedScene, VideoBrief, VideoConcept } from '../core/types';
import type { Storyboard } from '../remotion/contract/storyboard';
import { computeTimeline } from '../remotion/contract/timeline';

const sec = (frames: number, fps: number) => `${(frames / fps).toFixed(1)}s`;

export const scriptMarkdown = (brief: VideoBrief, concept: VideoConcept, storyboard: Storyboard): string => {
  const { fps } = storyboard.format;
  const timeline = computeTimeline(storyboard.scenes);
  const lines = [
    `# ${concept.title}`,
    '',
    brief.prompt.split('\n').map((l) => `> ${l}`.trimEnd()).join('\n'),
    '',
    '## Concept',
    '',
    `- **Idée** : ${concept.idea}`,
    `- **Angle** : ${concept.angle}`,
    `- **Ton** : ${concept.tone}`,
    `- **Message clé** : ${concept.keyMessage}`,
    `- **Appel à l’action** : ${concept.callToAction}`,
    `- **Signature** : ${concept.tagline}`,
    '',
    `## Script (${storyboard.scenes.length} scènes, ${sec(storyboard.format.durationInFrames, fps)}, ${storyboard.format.width}×${storyboard.format.height} @ ${fps} fps)`,
    '',
  ];
  storyboard.scenes.forEach((scene, i) => {
    const w = timeline[i]!;
    lines.push(`### ${i + 1}. ${scene.role} — \`${scene.kind}\` (${sec(w.from, fps)} → ${sec(w.from + w.durationInFrames, fps)})`, '');
    if (scene.subheadline) lines.push(`- Sur-titre : ${scene.subheadline}`);
    lines.push(`- Titre : ${scene.headline}`);
    if (scene.body) lines.push(`- Texte : ${scene.body}`);
    if (scene.items.length) lines.push(`- Éléments : ${scene.items.join(' · ')}`);
    if (scene.stat) lines.push(`- Chiffre : ${scene.stat.value} — ${scene.stat.label}`);
    if (scene.media) lines.push(`- Visuel : \`${scene.media.src}\` (${scene.media.origin})`);
    lines.push(`- Voix-off : « ${scene.narration} »`, '');
  });
  return lines.join('\n');
};

export const plannedScenesMarkdown = (scenes: PlannedScene[]): string =>
  scenes.map((s, i) => `${i + 1}. [${s.role}/${s.kind}] ${s.headline} — ${s.narration}`).join('\n');

export const jobReadme = (jobDir: string, storyboard: Storyboard, videoFile: string | undefined, repoRoot: string): string => `# ${storyboard.meta.title}

Generated by **SOVID AI** from the brief:

> ${storyboard.meta.prompt}

| File | Content |
| --- | --- |
| \`storyboard.json\` | Full Remotion storyboard (input props of the \`VideoAgent\` composition) |
| \`props.json\` | \`{ "storyboard": ... }\`, ready for \`remotion render --props\` |
| \`script.md\` | Concept and script, scene by scene |
| \`subtitles.srt\` / \`subtitles.vtt\` | Subtitles |
| \`public/\` | Assets used by the video (media, voice-over, music) |
| ${videoFile ? `\`${videoFile}\`` : '—'} | Final video |

## Edit and re-render

1. Edit \`storyboard.json\` (texts, durations, colours, scenes...).
2. Re-render:

\`\`\`bash
video-agent render "${jobDir}"
\`\`\`

## Open in Remotion Studio

\`\`\`bash
video-agent studio "${jobDir}"
# or, from ${repoRoot}:
npx remotion studio src/remotion/index.ts --props="${jobDir}/props.json" --public-dir="${jobDir}/public"
\`\`\`
`;
